export const LANGUAGES = [
  { code: 'en', label: 'English', speech: 'en-IN' },
  { code: 'hi', label: 'हिन्दी', speech: 'hi-IN' },
  { code: 'kn', label: 'ಕನ್ನಡ', speech: 'kn-IN' },
  { code: 'ta', label: 'தமிழ்', speech: 'ta-IN' },
  { code: 'te', label: 'తెలుగు', speech: 'te-IN' },
  { code: 'ml', label: 'മലയാളം', speech: 'ml-IN' },
  { code: 'bn', label: 'বাংলা', speech: 'bn-IN' },
  { code: 'mr', label: 'मराठी', speech: 'mr-IN' },
  { code: 'gu', label: 'ગુજરાતી', speech: 'gu-IN' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ', speech: 'pa-IN' },
  { code: 'or', label: 'ଓଡ଼ିଆ', speech: 'or-IN' },
  { code: 'as', label: 'অসমীয়া', speech: 'as-IN' },
  { code: 'ur', label: 'اردو', speech: 'ur-PK' },
] as const;

export type LanguageCode = typeof LANGUAGES[number]['code'];

const EN = {
  appSubtitle: 'Weather & Disaster Intelligence',
  overview: 'Overview', assistant: 'WeatherGPT AI', alertsRisk: 'Alerts & Risk', decisionCenter: 'Decision Center', climate: 'Climate Intelligence', weatherMap: 'Weather Map',
  location: 'Location', country: 'Country', state: 'State / Region', district: 'District / City', place: 'Place',
  selectCountry: 'Select country', selectState: 'Select state / region', selectDistrict: 'Select district / city', typePlace: 'Type a place…',
  useCurrent: 'Use current location', detecting: 'Detecting location…', locationHelp: 'Choose Country → State → District/City, type a place, or use GPS.',
  language: 'Language', voiceAssistant: 'Voice Assistant', askByVoice: 'Ask by voice',
  riskLevel: 'Risk Level', highRiskMeasures: 'High-risk safety measures', mediumRiskMeasures: 'Medium-risk precautions',
  riskHigh: 'High', riskMedium: 'Medium', riskLow: 'Low',
  introEyebrow: 'Conversational weather intelligence', introA: 'Weather that explains ', introB: 'what happens next', introC: ' — and what to do.',
  introDesc: 'Live forecasting, multilingual AI, explainable risk, climate history and personalized decision support in one platform.',
  liveData: 'LIVE WEATHER DATA', cachedData: 'CACHED OFFLINE SNAPSHOT', feelsLike: 'feels like', humidity: 'Humidity', wind: 'Wind', precipitation: 'Precipitation', pressure: 'Pressure', cloudCover: 'Cloud cover', windDirection: 'Wind direction', airQuality: 'Air quality',
  forecastEyebrow: '7-day numerical forecast', extendedForecast: 'Extended Forecast', today: 'Today',
  riskEyebrow: 'explainable AI risk detection', impactEngine: 'Impact & Early-Warning Engine', flood: 'Flood', heat: 'Heat', storm: 'Storm', whyScore: 'Why this score?', noMajorHazard: 'No major forecast hazard threshold crossed', monitor: 'Continue monitoring as conditions change.',
  riskDisclaimer: 'Forecast-derived risk estimate — not an official disaster warning. Verify emergency alerts with authorized agencies.',
  officialEyebrow: 'authoritative warnings', officialWarnings: 'Official IMD Warnings', officialLive: 'LIVE / OFFICIAL', checkingWarnings: 'Checking India Meteorological Department warning data…', noOfficial: 'No matching official warning displayed', officialSource: 'IMD source', issued: 'Issued', day: 'Day',
  assistantEyebrow: 'grounded conversational AI', assistantTitle: 'WeatherGPT Assistant', askRain: 'Will it rain tomorrow?', askRisk: 'Any weather risk?', askTemp: 'What is the temperature?', askTravel: 'Best time to travel?', chatPlaceholder: 'Ask naturally about weather…', analyzing: 'Analyzing live weather and risk context…', readAloud: 'Read aloud',
  actionEyebrow: 'action intelligence', personalizedDecision: 'Personalized Decision Center', public: 'Public', farmer: 'Farmer', traveler: 'Traveler', disasterTeam: 'Disaster Team', smartWindow: 'Smart Action Window', risk: 'risk', dataEvidence: 'Data Behind the Advice', realData: 'REAL DATA',
  climateEyebrow: 'historical weather archive', climate10: '10-Year Climate Intelligence', tempTrend: 'Temperature trend', rainTrend: 'Rainfall trend', loadingClimate: 'Loading 10-year climate history…', climateUnavailable: 'Climate data unavailable',
  mapEyebrow: 'GIS location selection', mapTitle: 'Interactive Global Weather Map', clickAnywhere: 'Click anywhere', mapHelp: 'Select any location on the map. WeatherGPT will retrieve live weather and recalculate risks for that point.',
  loadingWeather: 'Connecting to live meteorological data…', loadingWeatherDesc: 'Loading forecast, air quality and location context.',
  gpsError: 'Could not access your current location. Please allow location permission.', noStates: 'No states found', noDistricts: 'No districts/cities found', searchNoResults: 'No matching places found',
  measuresTitle: 'Recommended actions', measureFlood: 'Avoid low-lying and waterlogged areas; follow local flood instructions.', measureWind: 'Stay away from weak structures and secure loose outdoor objects.', measureStorm: 'Move indoors during thunder/lightning and avoid open areas.', measureHeat: 'Limit outdoor exposure, use shade and drink enough water.', measureGeneral: 'Monitor official alerts and keep emergency contacts available.',
};

type Keys = keyof typeof EN;

type PartialDict = Partial<Record<Keys, string>>;

const D: Record<string, PartialDict> = {
  en: EN,
  hi: {
    appSubtitle:'मौसम और आपदा बुद्धिमत्ता', overview:'अवलोकन', assistant:'WeatherGPT एआई', alertsRisk:'चेतावनी और जोखिम', decisionCenter:'निर्णय केंद्र', climate:'जलवायु बुद्धिमत्ता', weatherMap:'मौसम मानचित्र',
    location:'स्थान', country:'देश', state:'राज्य / क्षेत्र', district:'जिला / शहर', place:'स्थान खोजें', selectCountry:'देश चुनें', selectState:'राज्य / क्षेत्र चुनें', selectDistrict:'जिला / शहर चुनें', typePlace:'स्थान टाइप करें…', useCurrent:'वर्तमान स्थान का उपयोग करें', detecting:'स्थान पता लगाया जा रहा है…', locationHelp:'देश → राज्य → जिला/शहर चुनें, स्थान टाइप करें या GPS उपयोग करें।', language:'भाषा', voiceAssistant:'वॉइस सहायक', askByVoice:'आवाज़ से पूछें', riskLevel:'जोखिम स्तर', highRiskMeasures:'उच्च जोखिम सुरक्षा उपाय', mediumRiskMeasures:'मध्यम जोखिम सावधानियाँ', riskHigh:'उच्च', riskMedium:'मध्यम', riskLow:'कम',
    introEyebrow:'संवादी मौसम बुद्धिमत्ता', introA:'मौसम जो बताए ', introB:'आगे क्या होगा', introC:' — और क्या करना है।', introDesc:'लाइव पूर्वानुमान, बहुभाषी एआई, स्पष्ट जोखिम, जलवायु इतिहास और व्यक्तिगत निर्णय सहायता एक ही मंच पर।', liveData:'लाइव मौसम डेटा', cachedData:'सहेजा गया ऑफलाइन डेटा', feelsLike:'महसूस होता है', humidity:'आर्द्रता', wind:'हवा', precipitation:'वर्षा', pressure:'दाब', cloudCover:'बादल आवरण', windDirection:'हवा की दिशा', airQuality:'वायु गुणवत्ता',
    forecastEyebrow:'7-दिन का संख्यात्मक पूर्वानुमान', extendedForecast:'विस्तारित पूर्वानुमान', today:'आज', riskEyebrow:'व्याख्यात्मक एआई जोखिम पहचान', impactEngine:'प्रभाव और प्रारंभिक चेतावनी इंजन', flood:'बाढ़', heat:'गर्मी', storm:'तूफान', whyScore:'यह स्कोर क्यों?', noMajorHazard:'कोई बड़ा पूर्वानुमान जोखिम सीमा पार नहीं हुई', monitor:'स्थिति बदलने पर निगरानी जारी रखें।', riskDisclaimer:'यह पूर्वानुमान-आधारित जोखिम अनुमान है, आधिकारिक आपदा चेतावनी नहीं।',
    officialEyebrow:'आधिकारिक चेतावनियाँ', officialWarnings:'आधिकारिक IMD चेतावनियाँ', officialLive:'लाइव / आधिकारिक', checkingWarnings:'IMD चेतावनी डेटा जाँचा जा रहा है…', noOfficial:'कोई मेल खाती आधिकारिक चेतावनी नहीं', officialSource:'IMD स्रोत', issued:'जारी', day:'दिन', assistantEyebrow:'डेटा-आधारित संवादी एआई', assistantTitle:'WeatherGPT सहायक', askRain:'क्या कल बारिश होगी?', askRisk:'कोई मौसम जोखिम है?', askTemp:'तापमान क्या है?', askTravel:'यात्रा का सबसे अच्छा समय?', chatPlaceholder:'मौसम के बारे में स्वाभाविक रूप से पूछें…', analyzing:'लाइव मौसम और जोखिम का विश्लेषण हो रहा है…', readAloud:'जोर से पढ़ें',
    actionEyebrow:'कार्य बुद्धिमत्ता', personalizedDecision:'व्यक्तिगत निर्णय केंद्र', public:'सार्वजनिक', farmer:'किसान', traveler:'यात्री', disasterTeam:'आपदा दल', smartWindow:'स्मार्ट कार्य समय', risk:'जोखिम', dataEvidence:'सलाह के पीछे का डेटा', realData:'वास्तविक डेटा', climateEyebrow:'ऐतिहासिक मौसम संग्रह', climate10:'10-वर्षीय जलवायु बुद्धिमत्ता', tempTrend:'तापमान रुझान', rainTrend:'वर्षा रुझान', loadingClimate:'10-वर्षीय जलवायु इतिहास लोड हो रहा है…', climateUnavailable:'जलवायु डेटा उपलब्ध नहीं', mapEyebrow:'GIS स्थान चयन', mapTitle:'इंटरैक्टिव वैश्विक मौसम मानचित्र', clickAnywhere:'कहीं भी क्लिक करें', mapHelp:'मानचित्र पर स्थान चुनें। WeatherGPT लाइव मौसम और जोखिम फिर से गणना करेगा।', loadingWeather:'लाइव मौसम डेटा से जुड़ रहा है…', loadingWeatherDesc:'पूर्वानुमान, वायु गुणवत्ता और स्थान संदर्भ लोड हो रहे हैं।', gpsError:'वर्तमान स्थान नहीं मिला। कृपया लोकेशन अनुमति दें।', measuresTitle:'सुझाए गए कदम', measureFlood:'निचले और जलभराव वाले क्षेत्रों से बचें; स्थानीय बाढ़ निर्देशों का पालन करें।', measureWind:'कमज़ोर संरचनाओं से दूर रहें और ढीली बाहरी वस्तुएँ सुरक्षित करें।', measureStorm:'गरज/बिजली के दौरान अंदर रहें और खुले क्षेत्रों से बचें।', measureHeat:'बाहर रहने का समय कम करें, छाया में रहें और पर्याप्त पानी पिएँ।', measureGeneral:'आधिकारिक चेतावनियाँ देखें और आपातकालीन संपर्क तैयार रखें।'
  },
  kn: {
    appSubtitle:'ಹವಾಮಾನ ಮತ್ತು ವಿಪತ್ತು ಬುದ್ಧಿಮತ್ತೆ', overview:'ಅವಲೋಕನ', assistant:'WeatherGPT ಎಐ', alertsRisk:'ಎಚ್ಚರಿಕೆ ಮತ್ತು ಅಪಾಯ', decisionCenter:'ನಿರ್ಧಾರ ಕೇಂದ್ರ', climate:'ಹವಾಮಾನ ಬುದ್ಧಿಮತ್ತೆ', weatherMap:'ಹವಾಮಾನ ನಕ್ಷೆ', location:'ಸ್ಥಳ', country:'ದೇಶ', state:'ರಾಜ್ಯ / ಪ್ರದೇಶ', district:'ಜಿಲ್ಲೆ / ನಗರ', place:'ಸ್ಥಳ ಹುಡುಕಿ', selectCountry:'ದೇಶ ಆಯ್ಕೆಮಾಡಿ', selectState:'ರಾಜ್ಯ / ಪ್ರದೇಶ ಆಯ್ಕೆಮಾಡಿ', selectDistrict:'ಜಿಲ್ಲೆ / ನಗರ ಆಯ್ಕೆಮಾಡಿ', typePlace:'ಸ್ಥಳ ಟೈಪ್ ಮಾಡಿ…', useCurrent:'ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ', detecting:'ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ…', locationHelp:'ದೇಶ → ರಾಜ್ಯ → ಜಿಲ್ಲೆ/ನಗರ ಆಯ್ಕೆಮಾಡಿ, ಸ್ಥಳ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ GPS ಬಳಸಿ.', language:'ಭಾಷೆ', voiceAssistant:'ಧ್ವನಿ ಸಹಾಯಕ', askByVoice:'ಧ್ವನಿಯಲ್ಲಿ ಕೇಳಿ', riskLevel:'ಅಪಾಯ ಮಟ್ಟ', highRiskMeasures:'ಹೆಚ್ಚಿನ ಅಪಾಯದ ಸುರಕ್ಷತಾ ಕ್ರಮಗಳು', mediumRiskMeasures:'ಮಧ್ಯಮ ಅಪಾಯದ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು', riskHigh:'ಹೆಚ್ಚು', riskMedium:'ಮಧ್ಯಮ', riskLow:'ಕಡಿಮೆ', introEyebrow:'ಸಂವಾದಾತ್ಮಕ ಹವಾಮಾನ ಬುದ್ಧಿಮತ್ತೆ', introA:'ಹವಾಮಾನವು ', introB:'ಮುಂದೆ ಏನಾಗುತ್ತದೆ', introC:' — ಮತ್ತು ಏನು ಮಾಡಬೇಕು ಎಂದು ತಿಳಿಸುತ್ತದೆ.', introDesc:'ಲೈವ್ ಮುನ್ಸೂಚನೆ, ಬಹುಭಾಷಾ ಎಐ, ಸ್ಪಷ್ಟ ಅಪಾಯ, ಹವಾಮಾನ ಇತಿಹಾಸ ಮತ್ತು ವೈಯಕ್ತಿಕ ನಿರ್ಧಾರ ಬೆಂಬಲ ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ.', liveData:'ಲೈವ್ ಹವಾಮಾನ ಡೇಟಾ', cachedData:'ಉಳಿಸಿದ ಆಫ್‌ಲೈನ್ ಡೇಟಾ', feelsLike:'ಅನುಭವ', humidity:'ಆರ್ದ್ರತೆ', wind:'ಗಾಳಿ', precipitation:'ಮಳೆ', pressure:'ಒತ್ತಡ', cloudCover:'ಮೋಡ ಆವರಣ', windDirection:'ಗಾಳಿಯ ದಿಕ್ಕು', airQuality:'ವಾಯು ಗುಣಮಟ್ಟ', extendedForecast:'ವಿಸ್ತೃತ ಮುನ್ಸೂಚನೆ', today:'ಇಂದು', impactEngine:'ಪ್ರಭಾವ ಮತ್ತು ಮುನ್ನೆಚ್ಚರಿಕೆ ಎಂಜಿನ್', flood:'ಪ್ರವಾಹ', heat:'ಬಿಸಿಲು', storm:'ಬಿರುಗಾಳಿ', whyScore:'ಈ ಅಂಕ ಏಕೆ?', noMajorHazard:'ಪ್ರಮುಖ ಮುನ್ಸೂಚನಾ ಅಪಾಯ ಮಿತಿ ದಾಟಿಲ್ಲ', monitor:'ಪರಿಸ್ಥಿತಿ ಬದಲಾಗುವಂತೆ ಗಮನಿಸಿ.', officialWarnings:'ಅಧಿಕೃತ IMD ಎಚ್ಚರಿಕೆಗಳು', checkingWarnings:'IMD ಎಚ್ಚರಿಕೆ ಡೇಟಾ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…', noOfficial:'ಹೊಂದುವ ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆ ಇಲ್ಲ', assistantTitle:'WeatherGPT ಸಹಾಯಕ', askRain:'ನಾಳೆ ಮಳೆ ಬರುತ್ತದೆಯೇ?', askRisk:'ಯಾವುದೇ ಹವಾಮಾನ ಅಪಾಯ ಇದೆಯೇ?', askTemp:'ತಾಪಮಾನ ಎಷ್ಟು?', askTravel:'ಪ್ರಯಾಣಕ್ಕೆ ಉತ್ತಮ ಸಮಯ?', chatPlaceholder:'ಹವಾಮಾನ ಕುರಿತು ಕೇಳಿ…', analyzing:'ಲೈವ್ ಹವಾಮಾನ ಮತ್ತು ಅಪಾಯ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…', public:'ಸಾರ್ವಜನಿಕ', farmer:'ರೈತ', traveler:'ಪ್ರಯಾಣಿಕ', disasterTeam:'ವಿಪತ್ತು ತಂಡ', personalizedDecision:'ವೈಯಕ್ತಿಕ ನಿರ್ಧಾರ ಕೇಂದ್ರ', climate10:'10 ವರ್ಷದ ಹವಾಮಾನ ಬುದ್ಧಿಮತ್ತೆ', mapTitle:'ಅಂತರಕ್ರಿಯಾತ್ಮಕ ಜಾಗತಿಕ ಹವಾಮಾನ ನಕ್ಷೆ', mapHelp:'ನಕ್ಷೆಯಲ್ಲಿ ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ. WeatherGPT ಲೈವ್ ಹವಾಮಾನ ಮತ್ತು ಅಪಾಯವನ್ನು ಮರುಗಣಿಸುತ್ತದೆ.', loadingWeather:'ಲೈವ್ ಹವಾಮಾನ ಡೇಟಾಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ…', gpsError:'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಪಡೆಯಲಾಗಲಿಲ್ಲ. ಸ್ಥಳ ಅನುಮತಿ ನೀಡಿ.', measuresTitle:'ಶಿಫಾರಸು ಕ್ರಮಗಳು', measureFlood:'ತಗ್ಗು ಮತ್ತು ನೀರು ನಿಲ್ಲುವ ಪ್ರದೇಶಗಳನ್ನು ತಪ್ಪಿಸಿ; ಸ್ಥಳೀಯ ಪ್ರವಾಹ ಸೂಚನೆ ಅನುಸರಿಸಿ.', measureWind:'ದುರ್ಬಲ ಕಟ್ಟಡಗಳಿಂದ ದೂರಿರಿ ಮತ್ತು ಹೊರಗಿನ ಸಡಿಲ ವಸ್ತುಗಳನ್ನು ಸುರಕ್ಷಿತಗೊಳಿಸಿ.', measureStorm:'ಗುಡುಗು/ಮಿಂಚಿನ ವೇಳೆ ಒಳಗೆಿರಿ ಮತ್ತು ತೆರೆಯ ಪ್ರದೇಶ ತಪ್ಪಿಸಿ.', measureHeat:'ಹೊರಗಿರುವ ಸಮಯ ಕಡಿಮೆ ಮಾಡಿ, ನೆರಳಿನಲ್ಲಿ ಇರಿ ಮತ್ತು ಸಾಕಷ್ಟು ನೀರು ಕುಡಿಯಿರಿ.', measureGeneral:'ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಗಮನಿಸಿ ಮತ್ತು ತುರ್ತು ಸಂಪರ್ಕಗಳನ್ನು ಸಿದ್ಧವಾಗಿಡಿ.'
  },
  ta: { overview:'கண்ணோட்டம்', assistant:'WeatherGPT AI', alertsRisk:'எச்சரிக்கை & அபாயம்', decisionCenter:'முடிவு மையம்', climate:'காலநிலை நுண்ணறிவு', weatherMap:'வானிலை வரைபடம்', location:'இடம்', country:'நாடு', state:'மாநிலம் / பகுதி', district:'மாவட்டம் / நகரம்', place:'இடம் தேடுக', selectCountry:'நாட்டை தேர்வு செய்க', selectState:'மாநிலம் / பகுதியை தேர்வு செய்க', selectDistrict:'மாவட்டம் / நகரத்தை தேர்வு செய்க', typePlace:'இடத்தை தட்டச்சு செய்க…', useCurrent:'தற்போதைய இடத்தை பயன்படுத்து', detecting:'இடம் கண்டறியப்படுகிறது…', language:'மொழி', voiceAssistant:'குரல் உதவியாளர்', askByVoice:'குரலில் கேளுங்கள்', riskLevel:'அபாய நிலை', riskHigh:'உயர்', riskMedium:'மிதமான', riskLow:'குறைவு', highRiskMeasures:'உயர் அபாய பாதுகாப்பு நடவடிக்கைகள்', mediumRiskMeasures:'மிதமான அபாய முன்னெச்சரிக்கைகள்', introEyebrow:'உரையாடல் வானிலை நுண்ணறிவு', introA:'வானிலை ', introB:'அடுத்து என்ன நடக்கும்', introC:' — என்ன செய்ய வேண்டும் என்பதையும் சொல்கிறது.', introDesc:'நேரடி முன்னறிவிப்பு, பல்மொழி AI, விளக்கமான அபாயம், காலநிலை வரலாறு மற்றும் தனிப்பயன் முடிவு ஆதரவு.', liveData:'நேரடி வானிலை தரவு', cachedData:'சேமிக்கப்பட்ட ஆஃப்லைன் தரவு', feelsLike:'உணரப்படும்', humidity:'ஈரப்பதம்', wind:'காற்று', precipitation:'மழைப்பொழிவு', pressure:'அழுத்தம்', cloudCover:'மேக மூடல்', windDirection:'காற்றுத் திசை', airQuality:'காற்றுத் தரம்', extendedForecast:'விரிவான முன்னறிவிப்பு', today:'இன்று', impactEngine:'தாக்கம் & முன்எச்சரிக்கை இயந்திரம்', flood:'வெள்ளம்', heat:'வெப்பம்', storm:'புயல்', whyScore:'இந்த மதிப்பெண் ஏன்?', noMajorHazard:'பெரிய முன்னறிவிப்பு அபாய எல்லை கடக்கப்படவில்லை', monitor:'நிலை மாறும்போது தொடர்ந்து கண்காணிக்கவும்.', officialWarnings:'அதிகாரப்பூர்வ IMD எச்சரிக்கைகள்', assistantTitle:'WeatherGPT உதவியாளர்', askRain:'நாளை மழை பெய்யுமா?', askRisk:'வானிலை அபாயம் உள்ளதா?', askTemp:'வெப்பநிலை என்ன?', askTravel:'பயணத்திற்கு சிறந்த நேரம்?', chatPlaceholder:'வானிலை பற்றி கேளுங்கள்…', analyzing:'நேரடி வானிலை மற்றும் அபாயம் பகுப்பாய்வு செய்யப்படுகிறது…', public:'பொது', farmer:'விவசாயி', traveler:'பயணி', disasterTeam:'பேரிடர் குழு', personalizedDecision:'தனிப்பயன் முடிவு மையம்', climate10:'10 ஆண்டு காலநிலை நுண்ணறிவு', mapTitle:'உலகளாவிய வானிலை வரைபடம்', loadingWeather:'நேரடி வானிலை தரவுடன் இணைகிறது…', gpsError:'தற்போதைய இடத்தை அணுக முடியவில்லை. இட அனுமதியை வழங்கவும்.', measuresTitle:'பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்', measureFlood:'தாழ்வான மற்றும் நீர் தேங்கும் பகுதிகளை தவிர்த்து உள்ளூர் வெள்ள அறிவுறுத்தல்களை பின்பற்றவும்.', measureWind:'பலவீனமான கட்டிடங்களிலிருந்து விலகி, வெளிப்புற தளர்ந்த பொருட்களை பாதுகாக்கவும்.', measureStorm:'இடி/மின்னலின் போது உள்ளே சென்று திறந்த இடங்களை தவிர்க்கவும்.', measureHeat:'வெளிப்புற நேரத்தை குறைத்து, நிழலில் இருந்து போதுமான நீர் குடிக்கவும்.', measureGeneral:'அதிகாரப்பூர்வ எச்சரிக்கைகளை கண்காணித்து அவசர தொடர்புகளை தயார் வைத்திருங்கள்.' },
  te: { overview:'అవలోకనం', assistant:'WeatherGPT AI', alertsRisk:'హెచ్చరికలు & ప్రమాదం', decisionCenter:'నిర్ణయ కేంద్రం', climate:'వాతావరణ విశ్లేషణ', weatherMap:'వాతావరణ మ్యాప్', location:'స్థానం', country:'దేశం', state:'రాష్ట్రం / ప్రాంతం', district:'జిల్లా / నగరం', place:'స్థలం వెతకండి', selectCountry:'దేశాన్ని ఎంచుకోండి', selectState:'రాష్ట్రం / ప్రాంతం ఎంచుకోండి', selectDistrict:'జిల్లా / నగరం ఎంచుకోండి', typePlace:'స్థలం టైప్ చేయండి…', useCurrent:'ప్రస్తుత స్థానాన్ని ఉపయోగించండి', detecting:'స్థానం గుర్తిస్తోంది…', language:'భాష', voiceAssistant:'వాయిస్ అసిస్టెంట్', askByVoice:'వాయిస్‌తో అడగండి', riskLevel:'ప్రమాద స్థాయి', riskHigh:'అధిక', riskMedium:'మధ్యస్థ', riskLow:'తక్కువ', highRiskMeasures:'అధిక ప్రమాద భద్రతా చర్యలు', mediumRiskMeasures:'మధ్యస్థ ప్రమాద జాగ్రత్తలు', introEyebrow:'సంభాషణాత్మక వాతావరణ మేధస్సు', introA:'వాతావరణం ', introB:'తర్వాత ఏమవుతుంది', introC:' — ఏమి చేయాలో చెబుతుంది.', introDesc:'లైవ్ ఫోర్‌కాస్ట్, బహుభాషా AI, వివరించగల ప్రమాదం, వాతావరణ చరిత్ర మరియు వ్యక్తిగత నిర్ణయ సహాయం.', liveData:'లైవ్ వాతావరణ డేటా', feelsLike:'అనిపించే', humidity:'తేమ', wind:'గాలి', precipitation:'వర్షపాతం', pressure:'పీడనం', cloudCover:'మేఘావరణం', windDirection:'గాలి దిశ', airQuality:'గాలి నాణ్యత', extendedForecast:'విస్తృత ఫోర్‌కాస్ట్', today:'ఈరోజు', impactEngine:'ప్రభావం & ముందస్తు హెచ్చరిక ఇంజిన్', flood:'వరద', heat:'వేడి', storm:'తుఫాను', whyScore:'ఈ స్కోరు ఎందుకు?', officialWarnings:'అధికారిక IMD హెచ్చరికలు', assistantTitle:'WeatherGPT సహాయకుడు', askRain:'రేపు వర్షం పడుతుందా?', askRisk:'వాతావరణ ప్రమాదం ఉందా?', askTemp:'ఉష్ణోగ్రత ఎంత?', askTravel:'ప్రయాణానికి మంచి సమయం?', chatPlaceholder:'వాతావరణం గురించి అడగండి…', analyzing:'లైవ్ వాతావరణం మరియు ప్రమాదాన్ని విశ్లేషిస్తోంది…', public:'ప్రజలు', farmer:'రైతు', traveler:'ప్రయాణికుడు', disasterTeam:'విపత్తు బృందం', personalizedDecision:'వ్యక్తిగత నిర్ణయ కేంద్రం', climate10:'10 ఏళ్ల వాతావరణ విశ్లేషణ', mapTitle:'ఇంటరాక్టివ్ గ్లోబల్ వాతావరణ మ్యాప్', loadingWeather:'లైవ్ వాతావరణ డేటాకు కనెక్ట్ అవుతోంది…', gpsError:'ప్రస్తుత స్థానాన్ని పొందలేకపోయాం. లొకేషన్ అనుమతి ఇవ్వండి.', measuresTitle:'సిఫార్సు చర్యలు', measureFlood:'తక్కువ ప్రాంతాలు మరియు నీరు నిలిచే ప్రాంతాలను నివారించి స్థానిక వరద సూచనలను అనుసరించండి.', measureWind:'బలహీన నిర్మాణాల నుంచి దూరంగా ఉండి బయట ఉన్న సడలిన వస్తువులను భద్రపరచండి.', measureStorm:'ఉరుములు/మెరుపుల సమయంలో లోపలికి వెళ్లి బహిరంగ ప్రదేశాలను నివారించండి.', measureHeat:'బయట గడిపే సమయాన్ని తగ్గించి నీడలో ఉండి తగినంత నీరు తాగండి.', measureGeneral:'అధికారిక హెచ్చరికలను గమనించి అత్యవసర సంప్రదింపులను సిద్ధంగా ఉంచండి.' },
  ml: { overview:'അവലോകനം', assistant:'WeatherGPT AI', alertsRisk:'മുന്നറിയിപ്പുകളും അപകടവും', decisionCenter:'തീരുമാന കേന്ദ്രം', climate:'കാലാവസ്ഥ ബുദ്ധിമत्ता', weatherMap:'കാലാവസ്ഥ മാപ്പ്', location:'സ്ഥലം', country:'രാജ്യം', state:'സംസ്ഥാനം / പ്രദേശം', district:'ജില്ല / നഗരം', place:'സ്ഥലം തിരയുക', selectCountry:'രാജ്യം തിരഞ്ഞെടുക്കുക', selectState:'സംസ്ഥാനം / പ്രദേശം തിരഞ്ഞെടുക്കുക', selectDistrict:'ജില്ല / നഗരം തിരഞ്ഞെടുക്കുക', typePlace:'സ്ഥലം ടൈപ്പ് ചെയ്യുക…', useCurrent:'നിലവിലെ സ്ഥലം ഉപയോഗിക്കുക', detecting:'സ്ഥലം കണ്ടെത്തുന്നു…', language:'ഭാഷ', voiceAssistant:'വോയ്സ് അസിസ്റ്റന്റ്', askByVoice:'ശബ്ദമായി ചോദിക്കുക', riskLevel:'അപകടനില', riskHigh:'ഉയർന്ന', riskMedium:'മധ്യമ', riskLow:'കുറവ്', highRiskMeasures:'ഉയർന്ന അപകട സുരക്ഷാ നടപടികൾ', mediumRiskMeasures:'മധ്യമ അപകട മുൻകരുതലുകൾ', introEyebrow:'സംഭാഷണ കാലാവസ്ഥ ബുദ്ധിമत्ता', introA:'കാലാവസ്ഥ ', introB:'അടുത്തത് എന്ത് സംഭവിക്കും', introC:' — എന്ത് ചെയ്യണം എന്നും പറയുന്നു.', introDesc:'ലൈവ് പ്രവചനം, ബഹുഭാഷ AI, വിശദീകരിക്കാവുന്ന അപകടം, കാലാവസ്ഥ ചരിത്രം, വ്യക്തിഗത തീരുമാനസഹായം.', liveData:'ലൈവ് കാലാവസ്ഥ ഡാറ്റ', feelsLike:'അനുഭവപ്പെടുന്നത്', humidity:'ഈർപ്പം', wind:'കാറ്റ്', precipitation:'മഴ', pressure:'മർദ്ദം', cloudCover:'മേഘാവരണം', windDirection:'കാറ്റിന്റെ ദിശ', airQuality:'വായു ഗുണനിലവാരം', extendedForecast:'വിപുലമായ പ്രവചനം', today:'ഇന്ന്', impactEngine:'പ്രഭാവ & മുൻകൂർ മുന്നറിയിപ്പ് എഞ്ചിൻ', flood:'വെള്ളപ്പൊക്കം', heat:'ചൂട്', storm:'കൊടുങ്കാറ്റ്', whyScore:'ഈ സ്കോർ എന്തുകൊണ്ട്?', officialWarnings:'ഔദ്യോഗിക IMD മുന്നറിയിപ്പുകൾ', assistantTitle:'WeatherGPT സഹായി', askRain:'നാളെ മഴ പെയ്യുമോ?', askRisk:'കാലാവസ്ഥാ അപകടമുണ്ടോ?', askTemp:'താപനില എത്ര?', askTravel:'യാത്രയ്ക്ക് നല്ല സമയം?', chatPlaceholder:'കാലാവസ്ഥയെക്കുറിച്ച് ചോദിക്കുക…', analyzing:'ലൈവ് കാലാവസ്ഥയും അപകടവും വിശകലനം ചെയ്യുന്നു…', public:'പൊതുജനം', farmer:'കർഷകൻ', traveler:'യാത്രക്കാരൻ', disasterTeam:'ദുരന്ത സംഘം', personalizedDecision:'വ്യക്തിഗത തീരുമാന കേന്ദ്രം', climate10:'10 വർഷ കാലാവസ്ഥ ബുദ്ധിമत्ता', mapTitle:'ഇന്ററാക്ടീവ് ആഗോള കാലാവസ്ഥ മാപ്പ്', loadingWeather:'ലൈവ് കാലാവസ്ഥാ ഡാറ്റയുമായി ബന്ധപ്പെടുന്നു…', gpsError:'നിലവിലെ സ്ഥലം ലഭ്യമല്ല. ലൊക്കേഷൻ അനുമതി നൽകുക.', measuresTitle:'ശുപാർശ ചെയ്യുന്ന നടപടികൾ', measureFlood:'താഴ്ന്നതും വെള്ളം കെട്ടിക്കിടക്കുന്നതുമായ പ്രദേശങ്ങൾ ഒഴിവാക്കി പ്രാദേശിക വെള്ളപ്പൊക്ക നിർദ്ദേശങ്ങൾ പാലിക്കുക.', measureWind:'ദുർബല ഘടനകളിൽ നിന്ന് അകന്നു നിൽക്കുകയും പുറത്തുള്ള ഇളകിയ വസ്തുക്കൾ സുരക്ഷിതമാക്കുകയും ചെയ്യുക.', measureStorm:'ഇടി/മിന്നൽ സമയത്ത് അകത്ത് പോകുകയും തുറന്ന പ്രദേശങ്ങൾ ഒഴിവാക്കുകയും ചെയ്യുക.', measureHeat:'പുറത്തെ സമയം കുറച്ച് നിഴലിൽ ഇരിക്കുക, മതിയായ വെള്ളം കുടിക്കുക.', measureGeneral:'ഔദ്യോഗിക മുന്നറിയിപ്പുകൾ നിരീക്ഷിച്ച് അടിയന്തര ബന്ധങ്ങൾ തയ്യാറാക്കുക.' },
  bn: { overview:'সংক্ষিপ্ত বিবরণ', assistant:'WeatherGPT AI', alertsRisk:'সতর্কতা ও ঝুঁকি', decisionCenter:'সিদ্ধান্ত কেন্দ্র', climate:'জলবায়ু বিশ্লেষণ', weatherMap:'আবহাওয়া মানচিত্র', location:'অবস্থান', country:'দেশ', state:'রাজ্য / অঞ্চল', district:'জেলা / শহর', place:'স্থান খুঁজুন', selectCountry:'দেশ নির্বাচন করুন', selectState:'রাজ্য / অঞ্চল নির্বাচন করুন', selectDistrict:'জেলা / শহর নির্বাচন করুন', typePlace:'স্থান টাইপ করুন…', useCurrent:'বর্তমান অবস্থান ব্যবহার করুন', detecting:'অবস্থান শনাক্ত হচ্ছে…', language:'ভাষা', voiceAssistant:'ভয়েস সহকারী', askByVoice:'কণ্ঠে জিজ্ঞাসা করুন', riskLevel:'ঝুঁকির স্তর', riskHigh:'উচ্চ', riskMedium:'মাঝারি', riskLow:'কম', highRiskMeasures:'উচ্চ ঝুঁকির নিরাপত্তা ব্যবস্থা', mediumRiskMeasures:'মাঝারি ঝুঁকির সতর্কতা', introEyebrow:'কথোপকথনভিত্তিক আবহাওয়া বুদ্ধিমত্তা', introA:'আবহাওয়া বলে ', introB:'এরপর কী হবে', introC:' — এবং কী করতে হবে।', introDesc:'লাইভ পূর্বাভাস, বহুভাষিক AI, ব্যাখ্যাযোগ্য ঝুঁকি, জলবায়ু ইতিহাস এবং ব্যক্তিগত সিদ্ধান্ত সহায়তা।', liveData:'লাইভ আবহাওয়া ডেটা', feelsLike:'অনুভূত', humidity:'আর্দ্রতা', wind:'বাতাস', precipitation:'বৃষ্টিপাত', pressure:'চাপ', cloudCover:'মেঘের আচ্ছাদন', windDirection:'বাতাসের দিক', airQuality:'বায়ুর মান', extendedForecast:'বর্ধিত পূর্বাভাস', today:'আজ', impactEngine:'প্রভাব ও আগাম সতর্কতা ইঞ্জিন', flood:'বন্যা', heat:'তাপ', storm:'ঝড়', whyScore:'এই স্কোর কেন?', officialWarnings:'সরকারি IMD সতর্কতা', assistantTitle:'WeatherGPT সহকারী', askRain:'কাল বৃষ্টি হবে?', askRisk:'আবহাওয়ার ঝুঁকি আছে?', askTemp:'তাপমাত্রা কত?', askTravel:'ভ্রমণের সেরা সময়?', chatPlaceholder:'আবহাওয়া সম্পর্কে জিজ্ঞাসা করুন…', analyzing:'লাইভ আবহাওয়া ও ঝুঁকি বিশ্লেষণ হচ্ছে…', public:'জনসাধারণ', farmer:'কৃষক', traveler:'ভ্রমণকারী', disasterTeam:'দুর্যোগ দল', personalizedDecision:'ব্যক্তিগত সিদ্ধান্ত কেন্দ্র', climate10:'১০ বছরের জলবায়ু বিশ্লেষণ', mapTitle:'ইন্টারেক্টিভ বিশ্ব আবহাওয়া মানচিত্র', loadingWeather:'লাইভ আবহাওয়া ডেটায় সংযোগ হচ্ছে…', gpsError:'বর্তমান অবস্থান পাওয়া যায়নি। অবস্থানের অনুমতি দিন.', measuresTitle:'প্রস্তাবিত ব্যবস্থা', measureFlood:'নিচু ও জলাবদ্ধ এলাকা এড়িয়ে স্থানীয় বন্যা নির্দেশনা অনুসরণ করুন.', measureWind:'দুর্বল কাঠামো থেকে দূরে থাকুন এবং বাইরে ঢিলা জিনিস নিরাপদ করুন.', measureStorm:'বজ্রপাতের সময় ঘরের ভিতরে যান এবং খোলা জায়গা এড়িয়ে চলুন.', measureHeat:'বাইরে থাকার সময় কমান, ছায়ায় থাকুন এবং পর্যাপ্ত পানি পান করুন.', measureGeneral:'সরকারি সতর্কতা পর্যবেক্ষণ করুন এবং জরুরি যোগাযোগ প্রস্তুত রাখুন.' },
  mr: { overview:'आढावा', assistant:'WeatherGPT AI', alertsRisk:'इशारे आणि धोका', decisionCenter:'निर्णय केंद्र', climate:'हवामान बुद्धिमत्ता', weatherMap:'हवामान नकाशा', location:'स्थान', country:'देश', state:'राज्य / प्रदेश', district:'जिल्हा / शहर', place:'ठिकाण शोधा', selectCountry:'देश निवडा', selectState:'राज्य / प्रदेश निवडा', selectDistrict:'जिल्हा / शहर निवडा', typePlace:'ठिकाण टाइप करा…', useCurrent:'सध्याचे स्थान वापरा', detecting:'स्थान शोधत आहे…', language:'भाषा', voiceAssistant:'व्हॉइस सहाय्यक', askByVoice:'आवाजाने विचारा', riskLevel:'धोका स्तर', riskHigh:'उच्च', riskMedium:'मध्यम', riskLow:'कमी', highRiskMeasures:'उच्च धोका सुरक्षा उपाय', mediumRiskMeasures:'मध्यम धोका खबरदारी', introEyebrow:'संवादी हवामान बुद्धिमत्ता', introA:'हवामान सांगते ', introB:'पुढे काय होईल', introC:' — आणि काय करावे.', introDesc:'लाइव्ह अंदाज, बहुभाषिक AI, स्पष्ट धोका, हवामान इतिहास आणि वैयक्तिक निर्णय सहाय्य.', liveData:'लाइव्ह हवामान डेटा', feelsLike:'जाणवते', humidity:'आर्द्रता', wind:'वारा', precipitation:'पर्जन्य', pressure:'दाब', cloudCover:'ढगांचे प्रमाण', windDirection:'वाऱ्याची दिशा', airQuality:'हवेची गुणवत्ता', extendedForecast:'विस्तारित अंदाज', today:'आज', impactEngine:'परिणाम आणि पूर्वसूचना इंजिन', flood:'पूर', heat:'उष्णता', storm:'वादळ', whyScore:'हा स्कोअर का?', officialWarnings:'अधिकृत IMD इशारे', assistantTitle:'WeatherGPT सहाय्यक', askRain:'उद्या पाऊस पडेल का?', askRisk:'हवामानाचा धोका आहे का?', askTemp:'तापमान किती आहे?', askTravel:'प्रवासासाठी सर्वोत्तम वेळ?', chatPlaceholder:'हवामानाबद्दल विचारा…', analyzing:'लाइव्ह हवामान आणि धोका विश्लेषित होत आहे…', public:'सार्वजनिक', farmer:'शेतकरी', traveler:'प्रवासी', disasterTeam:'आपत्ती पथक', personalizedDecision:'वैयक्तिक निर्णय केंद्र', climate10:'10 वर्ष हवामान बुद्धिमत्ता', mapTitle:'परस्परसंवादी जागतिक हवामान नकाशा', loadingWeather:'लाइव्ह हवामान डेटाशी जोडत आहे…', gpsError:'सध्याचे स्थान मिळाले नाही. कृपया स्थान परवानगी द्या.', measuresTitle:'शिफारस केलेली पावले', measureFlood:'सखल व पाणी साचणारे भाग टाळा आणि स्थानिक पूर सूचनांचे पालन करा.', measureWind:'कमकुवत संरचनांपासून दूर रहा आणि बाहेरील सैल वस्तू सुरक्षित करा.', measureStorm:'मेघगर्जना/विजेच्या वेळी घरात जा आणि मोकळी ठिकाणे टाळा.', measureHeat:'बाहेरचा वेळ कमी करा, सावलीत रहा आणि पुरेसे पाणी प्या.', measureGeneral:'अधिकृत इशारे पाहत रहा आणि आपत्कालीन संपर्क तयार ठेवा.' },
  gu: { overview:'ઝાંખી', assistant:'WeatherGPT AI', alertsRisk:'ચેતવણી અને જોખમ', decisionCenter:'નિર્ણય કેન્દ્ર', climate:'હવામાન બુદ્ધિમત્તા', weatherMap:'હવામાન નકશો', location:'સ્થાન', country:'દેશ', state:'રાજ્ય / વિસ્તાર', district:'જિલ્લો / શહેર', place:'સ્થળ શોધો', selectCountry:'દેશ પસંદ કરો', selectState:'રાજ્ય / વિસ્તાર પસંદ કરો', selectDistrict:'જિલ્લો / શહેર પસંદ કરો', typePlace:'સ્થળ લખો…', useCurrent:'વર્તમાન સ્થાન વાપરો', detecting:'સ્થાન શોધી રહ્યું છે…', language:'ભાષા', voiceAssistant:'વૉઇસ સહાયક', askByVoice:'આવાજથી પૂછો', riskLevel:'જોખમ સ્તર', riskHigh:'ઉચ્ચ', riskMedium:'મધ્યમ', riskLow:'ઓછું', highRiskMeasures:'ઉચ્ચ જોખમ સુરક્ષા પગલાં', mediumRiskMeasures:'મધ્યમ જોખમ સાવચેતી', introEyebrow:'વાતચીત આધારિત હવામાન બુદ્ધિમત્તા', introA:'હવામાન કહે છે ', introB:'આગળ શું થશે', introC:' — અને શું કરવું.', introDesc:'લાઇવ આગાહી, બહુભાષી AI, સમજાય તેવું જોખમ, હવામાન ઇતિહાસ અને વ્યક્તિગત નિર્ણય સહાય.', liveData:'લાઇવ હવામાન ડેટા', feelsLike:'અનુભવાય છે', humidity:'ભેજ', wind:'પવન', precipitation:'વરસાદ', pressure:'દબાણ', cloudCover:'વાદળ આવરણ', windDirection:'પવન દિશા', airQuality:'હવા ગુણવત્તા', extendedForecast:'વિસ્તૃત આગાહી', today:'આજે', impactEngine:'અસર અને પૂર્વચેતવણી એન્જિન', flood:'પૂર', heat:'ગરમી', storm:'તોફાન', whyScore:'આ સ્કોર કેમ?', officialWarnings:'અધિકૃત IMD ચેતવણીઓ', assistantTitle:'WeatherGPT સહાયક', askRain:'કાલે વરસાદ પડશે?', askRisk:'હવામાન જોખમ છે?', askTemp:'તાપમાન કેટલું છે?', askTravel:'મુસાફરી માટે શ્રેષ્ઠ સમય?', chatPlaceholder:'હવામાન વિશે પૂછો…', analyzing:'લાઇવ હવામાન અને જોખમનું વિશ્લેષણ થઈ રહ્યું છે…', public:'જાહેર', farmer:'ખેડૂત', traveler:'મુસાફર', disasterTeam:'આપત્તિ ટીમ', personalizedDecision:'વ્યક્તિગત નિર્ણય કેન્દ્ર', climate10:'10 વર્ષ હવામાન બુદ્ધિમત્તા', mapTitle:'ઇન્ટરએક્ટિવ વૈશ્વિક હવામાન નકશો', loadingWeather:'લાઇવ હવામાન ડેટા સાથે જોડાઈ રહ્યું છે…', gpsError:'વર્તમાન સ્થાન મેળવી શકાયું નથી. સ્થાન પરવાનગી આપો.', measuresTitle:'ભલામણ કરેલ પગલાં', measureFlood:'નીચાણ અને પાણી ભરાતા વિસ્તારો ટાળો અને સ્થાનિક પૂર સૂચનાઓ અનુસરો.', measureWind:'નબળી રચનાઓથી દૂર રહો અને બહારની ઢીલી વસ્તુઓ સુરક્ષિત કરો.', measureStorm:'ગરજ/વીજળી દરમિયાન અંદર જાઓ અને ખુલ્લા વિસ્તારો ટાળો.', measureHeat:'બહારનો સમય ઓછો કરો, છાયામાં રહો અને પૂરતું પાણી પીવો.', measureGeneral:'અધિકૃત ચેતવણીઓ જુઓ અને ઇમરજન્સી સંપર્ક તૈયાર રાખો.' },
  pa: { overview:'ਝਲਕ', assistant:'WeatherGPT AI', alertsRisk:'ਚੇਤਾਵਨੀ ਅਤੇ ਖਤਰਾ', decisionCenter:'ਫੈਸਲਾ ਕੇਂਦਰ', climate:'ਮੌਸਮ ਬੁੱਧੀ', weatherMap:'ਮੌਸਮ ਨਕਸ਼ਾ', location:'ਸਥਾਨ', country:'ਦੇਸ਼', state:'ਰਾਜ / ਖੇਤਰ', district:'ਜ਼ਿਲ੍ਹਾ / ਸ਼ਹਿਰ', place:'ਥਾਂ ਲੱਭੋ', selectCountry:'ਦੇਸ਼ ਚੁਣੋ', selectState:'ਰਾਜ / ਖੇਤਰ ਚੁਣੋ', selectDistrict:'ਜ਼ਿਲ੍ਹਾ / ਸ਼ਹਿਰ ਚੁਣੋ', typePlace:'ਥਾਂ ਟਾਈਪ ਕਰੋ…', useCurrent:'ਮੌਜੂਦਾ ਸਥਾਨ ਵਰਤੋ', detecting:'ਸਥਾਨ ਲੱਭ ਰਿਹਾ ਹੈ…', language:'ਭਾਸ਼ਾ', voiceAssistant:'ਵੌਇਸ ਸਹਾਇਕ', askByVoice:'ਆਵਾਜ਼ ਨਾਲ ਪੁੱਛੋ', riskLevel:'ਖਤਰੇ ਦਾ ਪੱਧਰ', riskHigh:'ਉੱਚ', riskMedium:'ਦਰਮਿਆਨਾ', riskLow:'ਘੱਟ', highRiskMeasures:'ਉੱਚ ਖਤਰੇ ਲਈ ਸੁਰੱਖਿਆ ਕਦਮ', mediumRiskMeasures:'ਦਰਮਿਆਨੇ ਖਤਰੇ ਦੀਆਂ ਸਾਵਧਾਨੀਆਂ', introEyebrow:'ਗੱਲਬਾਤੀ ਮੌਸਮ ਬੁੱਧੀ', introA:'ਮੌਸਮ ਦੱਸਦਾ ਹੈ ', introB:'ਅੱਗੇ ਕੀ ਹੋਵੇਗਾ', introC:' — ਅਤੇ ਕੀ ਕਰਨਾ ਹੈ।', introDesc:'ਲਾਈਵ ਭਵਿੱਖਬਾਣੀ, ਬਹੁਭਾਸ਼ੀ AI, ਸਮਝਣਯੋਗ ਖਤਰਾ, ਮੌਸਮ ਇਤਿਹਾਸ ਅਤੇ ਨਿੱਜੀ ਫੈਸਲਾ ਸਹਾਇਤਾ.', liveData:'ਲਾਈਵ ਮੌਸਮ ਡੇਟਾ', feelsLike:'ਮਹਿਸੂਸ', humidity:'ਨਮੀ', wind:'ਹਵਾ', precipitation:'ਵਰਖਾ', pressure:'ਦਬਾਅ', cloudCover:'ਬੱਦਲ ਕਵਰ', windDirection:'ਹਵਾ ਦੀ ਦਿਸ਼ਾ', airQuality:'ਹਵਾ ਗੁਣਵੱਤਾ', extendedForecast:'ਵਿਸਤ੍ਰਿਤ ਭਵਿੱਖਬਾਣੀ', today:'ਅੱਜ', impactEngine:'ਅਸਰ ਅਤੇ ਪਹਿਲਾਂ ਚੇਤਾਵਨੀ ਇੰਜਨ', flood:'ਹੜ੍ਹ', heat:'ਗਰਮੀ', storm:'ਤੂਫ਼ਾਨ', whyScore:'ਇਹ ਸਕੋਰ ਕਿਉਂ?', officialWarnings:'ਅਧਿਕਾਰਤ IMD ਚੇਤਾਵਨੀਆਂ', assistantTitle:'WeatherGPT ਸਹਾਇਕ', askRain:'ਕੀ ਕੱਲ੍ਹ ਮੀਂਹ ਪਵੇਗਾ?', askRisk:'ਕੋਈ ਮੌਸਮੀ ਖਤਰਾ ਹੈ?', askTemp:'ਤਾਪਮਾਨ ਕੀ ਹੈ?', askTravel:'ਸਫ਼ਰ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਸਮਾਂ?', chatPlaceholder:'ਮੌਸਮ ਬਾਰੇ ਪੁੱਛੋ…', analyzing:'ਲਾਈਵ ਮੌਸਮ ਅਤੇ ਖਤਰੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ…', public:'ਜਨਤਾ', farmer:'ਕਿਸਾਨ', traveler:'ਯਾਤਰੀ', disasterTeam:'ਆਫ਼ਤ ਟੀਮ', personalizedDecision:'ਨਿੱਜੀ ਫੈਸਲਾ ਕੇਂਦਰ', climate10:'10 ਸਾਲ ਮੌਸਮ ਬੁੱਧੀ', mapTitle:'ਇੰਟਰੈਕਟਿਵ ਗਲੋਬਲ ਮੌਸਮ ਨਕਸ਼ਾ', loadingWeather:'ਲਾਈਵ ਮੌਸਮ ਡੇਟਾ ਨਾਲ ਜੁੜ ਰਿਹਾ ਹੈ…', gpsError:'ਮੌਜੂਦਾ ਸਥਾਨ ਨਹੀਂ ਮਿਲਿਆ. ਕਿਰਪਾ ਕਰਕੇ ਸਥਾਨ ਦੀ ਆਗਿਆ ਦਿਓ.', measuresTitle:'ਸਿਫਾਰਸ਼ੀ ਕਦਮ', measureFlood:'ਨੀਵੇਂ ਅਤੇ ਪਾਣੀ ਭਰਨ ਵਾਲੇ ਇਲਾਕਿਆਂ ਤੋਂ ਬਚੋ ਅਤੇ ਸਥਾਨਕ ਹੜ੍ਹ ਹਦਾਇਤਾਂ ਮੰਨੋ.', measureWind:'ਕਮਜ਼ੋਰ ਢਾਂਚਿਆਂ ਤੋਂ ਦੂਰ ਰਹੋ ਅਤੇ ਬਾਹਰ ਦੀਆਂ ਢਿੱਲੀਆਂ ਚੀਜ਼ਾਂ ਸੁਰੱਖਿਅਤ ਕਰੋ.', measureStorm:'ਗਰਜ/ਬਿਜਲੀ ਦੌਰਾਨ ਅੰਦਰ ਜਾਓ ਅਤੇ ਖੁੱਲ੍ਹੇ ਇਲਾਕਿਆਂ ਤੋਂ ਬਚੋ.', measureHeat:'ਬਾਹਰ ਦਾ ਸਮਾਂ ਘਟਾਓ, ਛਾਂ ਵਿੱਚ ਰਹੋ ਅਤੇ ਕਾਫ਼ੀ ਪਾਣੀ ਪੀਓ.', measureGeneral:'ਅਧਿਕਾਰਤ ਚੇਤਾਵਨੀਆਂ ਵੇਖੋ ਅਤੇ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਤਿਆਰ ਰੱਖੋ.' },
  or: { overview:'ସାରାଂଶ', assistant:'WeatherGPT AI', alertsRisk:'ସତର୍କତା ଓ ବିପଦ', decisionCenter:'ନିଷ୍ପତ୍ତି କେନ୍ଦ୍ର', climate:'ଜଳବାୟୁ ବୁଦ୍ଧିମତା', weatherMap:'ପାଣିପାଗ ମାନଚିତ୍ର', location:'ସ୍ଥାନ', country:'ଦେଶ', state:'ରାଜ୍ୟ / ଅଞ୍ଚଳ', district:'ଜିଲ୍ଲା / ସହର', place:'ସ୍ଥାନ ଖୋଜନ୍ତୁ', selectCountry:'ଦେଶ ବାଛନ୍ତୁ', selectState:'ରାଜ୍ୟ / ଅଞ୍ଚଳ ବାଛନ୍ତୁ', selectDistrict:'ଜିଲ୍ଲା / ସହର ବାଛନ୍ତୁ', typePlace:'ସ୍ଥାନ ଟାଇପ କରନ୍ତୁ…', useCurrent:'ବର୍ତ୍ତମାନ ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ', language:'ଭାଷା', voiceAssistant:'ଭଏସ୍ ସହାୟକ', askByVoice:'ଭଏସ୍‌ରେ ପଚାରନ୍ତୁ', riskLevel:'ବିପଦ ସ୍ତର', riskHigh:'ଉଚ୍ଚ', riskMedium:'ମଧ୍ୟମ', riskLow:'କମ', highRiskMeasures:'ଉଚ୍ଚ ବିପଦ ସୁରକ୍ଷା ପଦକ୍ଷେପ', mediumRiskMeasures:'ମଧ୍ୟମ ବିପଦ ସାବଧାନତା', introEyebrow:'ସଂଭାଷଣାତ୍ମକ ପାଣିପାଗ ବୁଦ୍ଧିମତା', introA:'ପାଣିପାଗ କହେ ', introB:'ଆଗକୁ କଣ ହେବ', introC:' — ଏବଂ କଣ କରିବେ।', introDesc:'ଲାଇଭ୍ ପୂର୍ବାନୁମାନ, ବହୁଭାଷୀ AI, ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟ ବିପଦ, ଜଳବାୟୁ ଇତିହାସ ଓ ବ୍ୟକ୍ତିଗତ ନିଷ୍ପତ୍ତି ସହାୟତା.', liveData:'ଲାଇଭ୍ ପାଣିପାଗ ତଥ୍ୟ', feelsLike:'ଅନୁଭବ', humidity:'ଆର୍ଦ୍ରତା', wind:'ପବନ', precipitation:'ବର୍ଷା', pressure:'ଚାପ', cloudCover:'ମେଘ ଆବରଣ', windDirection:'ପବନ ଦିଗ', airQuality:'ବାୟୁ ଗୁଣବତ୍ତା', extendedForecast:'ବିସ୍ତୃତ ପୂର୍ବାନୁମାନ', today:'ଆଜି', impactEngine:'ପ୍ରଭାବ ଓ ପୂର୍ବ ସତର୍କତା ଇଞ୍ଜିନ୍', flood:'ବନ୍ୟା', heat:'ତାପ', storm:'ଝଡ଼', whyScore:'ଏହି ସ୍କୋର କାହିଁକି?', officialWarnings:'ଅଧିକୃତ IMD ସତର୍କତା', assistantTitle:'WeatherGPT ସହାୟକ', askRain:'ଆସନ୍ତାକାଲି ବର୍ଷା ହେବ କି?', askRisk:'କୌଣସି ପାଣିପାଗ ବିପଦ ଅଛି କି?', askTemp:'ତାପମାତ୍ରା କେତେ?', askTravel:'ଯାତ୍ରା ପାଇଁ ଭଲ ସମୟ?', chatPlaceholder:'ପାଣିପାଗ ବିଷୟରେ ପଚାରନ୍ତୁ…', analyzing:'ଲାଇଭ୍ ପାଣିପାଗ ଓ ବିପଦ ବିଶ୍ଳେଷଣ ହେଉଛି…', public:'ସାଧାରଣ', farmer:'ଚାଷୀ', traveler:'ଯାତ୍ରୀ', disasterTeam:'ବିପର୍ଯ୍ୟୟ ଦଳ', personalizedDecision:'ବ୍ୟକ୍ତିଗତ ନିଷ୍ପତ୍ତି କେନ୍ଦ୍ର', climate10:'10 ବର୍ଷ ଜଳବାୟୁ ବୁଦ୍ଧିମତା', mapTitle:'ଇଣ୍ଟରାକ୍ଟିଭ୍ ବିଶ୍ୱ ପାଣିପାଗ ମାନଚିତ୍ର', loadingWeather:'ଲାଇଭ୍ ପାଣିପାଗ ତଥ୍ୟ ସହ ଯୋଡ଼ାଯାଉଛି…', gpsError:'ବର୍ତ୍ତମାନ ସ୍ଥାନ ମିଳିଲା ନାହିଁ। ସ୍ଥାନ ଅନୁମତି ଦିଅନ୍ତୁ।', measuresTitle:'ପରାମର୍ଶିତ ପଦକ୍ଷେପ', measureFlood:'ନିମ୍ନ ଏବଂ ଜଳମଗ୍ନ ଅଞ୍ଚଳ ଏଡ଼ାନ୍ତୁ ଓ ସ୍ଥାନୀୟ ବନ୍ୟା ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ।', measureWind:'ଦୁର୍ବଳ ଗଠନରୁ ଦୂରେ ରୁହନ୍ତୁ ଓ ବାହାର ଢିଲା ବସ୍ତୁ ସୁରକ୍ଷିତ କରନ୍ତୁ।', measureStorm:'ବଜ୍ରପାତ ସମୟରେ ଘରଭିତରେ ଯାଆନ୍ତୁ ଓ ଖୋଲା ସ୍ଥାନ ଏଡ଼ାନ୍ତୁ।', measureHeat:'ବାହାର ସମୟ କମାନ୍ତୁ, ଛାୟାରେ ରୁହନ୍ତୁ ଓ ପର୍ଯ୍ୟାପ୍ତ ପାଣି ପିଅନ୍ତୁ।', measureGeneral:'ଅଧିକୃତ ସତର୍କତା ଦେଖନ୍ତୁ ଓ ଜରୁରୀ ସମ୍ପର୍କ ପ୍ରସ୍ତୁତ ରଖନ୍ତୁ।' },
  as: { overview:'সাৰাংশ', assistant:'WeatherGPT AI', alertsRisk:'সতৰ্কতা আৰু বিপদ', decisionCenter:'সিদ্ধান্ত কেন্দ্ৰ', climate:'জলবায়ু বুদ্ধিমত্তা', weatherMap:'বতৰ মানচিত্ৰ', location:'স্থান', country:'দেশ', state:'ৰাজ্য / অঞ্চল', district:'জিলা / চহৰ', place:'স্থান সন্ধান', selectCountry:'দেশ বাছক', selectState:'ৰাজ্য / অঞ্চল বাছক', selectDistrict:'জিলা / চহৰ বাছক', typePlace:'স্থান টাইপ কৰক…', useCurrent:'বৰ্তমান স্থান ব্যৱহাৰ কৰক', language:'ভাষা', voiceAssistant:'ভইচ সহায়ক', askByVoice:'কণ্ঠেৰে সোধক', riskLevel:'বিপদ স্তৰ', riskHigh:'উচ্চ', riskMedium:'মধ্যম', riskLow:'কম', highRiskMeasures:'উচ্চ বিপদৰ সুৰক্ষা ব্যৱস্থা', mediumRiskMeasures:'মধ্যম বিপদৰ সাৱধানতা', introEyebrow:'কথোপকথনভিত্তিক বতৰ বুদ্ধিমত্তা', introA:'বতৰে কয় ', introB:'আগলৈ কি হ’ব', introC:' — আৰু কি কৰিব লাগে।', introDesc:'লাইভ পূৰ্বানুমান, বহুভাষিক AI, ব্যাখ্যাযোগ্য বিপদ, জলবায়ু ইতিহাস আৰু ব্যক্তিগত সিদ্ধান্ত সহায়তা.', liveData:'লাইভ বতৰ তথ্য', feelsLike:'অনুভৱ', humidity:'আৰ্দ্ৰতা', wind:'বতাহ', precipitation:'বৰষুণ', pressure:'চাপ', cloudCover:'মেঘ আৱৰণ', windDirection:'বতাহৰ দিশ', airQuality:'বায়ু গুণমান', extendedForecast:'বিস্তৃত পূৰ্বানুমান', today:'আজি', impactEngine:'প্ৰভাৱ আৰু আগজাননী ইঞ্জিন', flood:'বানপানী', heat:'গৰম', storm:'ধুমুহা', whyScore:'এই স্ক’ৰ কিয়?', officialWarnings:'অধিকৃত IMD সতৰ্কতা', assistantTitle:'WeatherGPT সহায়ক', askRain:'কাইলৈ বৰষুণ হ’ব নেকি?', askRisk:'বতৰৰ কোনো বিপদ আছে নেকি?', askTemp:'উষ্ণতা কিমান?', askTravel:'যাত্ৰাৰ ভাল সময়?', chatPlaceholder:'বতৰৰ বিষয়ে সোধক…', analyzing:'লাইভ বতৰ আৰু বিপদ বিশ্লেষণ কৰা হৈছে…', public:'সাধাৰণ', farmer:'কৃষক', traveler:'যাত্ৰী', disasterTeam:'দুৰ্যোগ দল', personalizedDecision:'ব্যক্তিগত সিদ্ধান্ত কেন্দ্ৰ', climate10:'10 বছৰৰ জলবায়ু বুদ্ধিমত্তা', mapTitle:'ইণ্টাৰেক্টিভ বিশ্ব বতৰ মানচিত্ৰ', loadingWeather:'লাইভ বতৰ তথ্যৰ সৈতে সংযোগ কৰা হৈছে…', gpsError:'বৰ্তমান স্থান পোৱা নগ’ল। স্থান অনুমতি দিয়ক।', measuresTitle:'পৰামৰ্শিত পদক্ষেপ', measureFlood:'নিম্ন আৰু জলমগ্ন এলাকা এৰাই চলক আৰু স্থানীয় বানপানীৰ নিৰ্দেশ মানক।', measureWind:'দুৰ্বল গঠনসমূহৰ পৰা আঁতৰি থাকক আৰু বাহিৰৰ ঢিলা বস্তু সুৰক্ষিত কৰক।', measureStorm:'গাজনি/বিজুলীৰ সময়ত ভিতৰলৈ যাওক আৰু মুকলি ঠাই এৰাই চলক।', measureHeat:'বাহিৰত থকা সময় কমাওক, ছাঁত থাকক আৰু যথেষ্ট পানী খাওক।', measureGeneral:'অধিকৃত সতৰ্কতা চাই থাকক আৰু জৰুৰী যোগাযোগ সাজু ৰাখক।' },
  ur: { overview:'جائزہ', assistant:'WeatherGPT AI', alertsRisk:'انتباہ اور خطرہ', decisionCenter:'فیصلہ مرکز', climate:'موسمیاتی ذہانت', weatherMap:'موسم کا نقشہ', location:'مقام', country:'ملک', state:'صوبہ / علاقہ', district:'ضلع / شہر', place:'جگہ تلاش کریں', selectCountry:'ملک منتخب کریں', selectState:'صوبہ / علاقہ منتخب کریں', selectDistrict:'ضلع / شہر منتخب کریں', typePlace:'جگہ لکھیں…', useCurrent:'موجودہ مقام استعمال کریں', detecting:'مقام معلوم کیا جا رہا ہے…', language:'زبان', voiceAssistant:'وائس اسسٹنٹ', askByVoice:'آواز سے پوچھیں', riskLevel:'خطرے کی سطح', riskHigh:'زیادہ', riskMedium:'درمیانہ', riskLow:'کم', highRiskMeasures:'زیادہ خطرے کے حفاظتی اقدامات', mediumRiskMeasures:'درمیانے خطرے کی احتیاط', introEyebrow:'گفتگو پر مبنی موسمی ذہانت', introA:'موسم بتاتا ہے ', introB:'آگے کیا ہوگا', introC:' — اور کیا کرنا ہے۔', introDesc:'لائیو پیش گوئی، کثیر لسانی AI، واضح خطرہ، موسمی تاریخ اور ذاتی فیصلہ سازی کی مدد.', liveData:'لائیو موسم ڈیٹا', feelsLike:'محسوس', humidity:'نمی', wind:'ہوا', precipitation:'بارش', pressure:'دباؤ', cloudCover:'بادل', windDirection:'ہوا کی سمت', airQuality:'ہوا کا معیار', extendedForecast:'تفصیلی پیش گوئی', today:'آج', impactEngine:'اثرات اور ابتدائی انتباہ انجن', flood:'سیلاب', heat:'گرمی', storm:'طوفان', whyScore:'یہ اسکور کیوں؟', officialWarnings:'سرکاری IMD انتباہات', assistantTitle:'WeatherGPT معاون', askRain:'کیا کل بارش ہوگی؟', askRisk:'کوئی موسمی خطرہ ہے؟', askTemp:'درجہ حرارت کیا ہے؟', askTravel:'سفر کا بہترین وقت؟', chatPlaceholder:'موسم کے بارے میں پوچھیں…', analyzing:'لائیو موسم اور خطرے کا تجزیہ ہو رہا ہے…', public:'عوام', farmer:'کسان', traveler:'مسافر', disasterTeam:'آفات ٹیم', personalizedDecision:'ذاتی فیصلہ مرکز', climate10:'10 سالہ موسمیاتی ذہانت', mapTitle:'انٹرایکٹو عالمی موسم کا نقشہ', loadingWeather:'لائیو موسم ڈیٹا سے رابطہ ہو رہا ہے…', gpsError:'موجودہ مقام حاصل نہیں ہو سکا۔ مقام کی اجازت دیں۔', measuresTitle:'تجویز کردہ اقدامات', measureFlood:'نشیبی اور پانی بھرنے والے علاقوں سے بچیں اور مقامی سیلاب ہدایات پر عمل کریں۔', measureWind:'کمزور ڈھانچوں سے دور رہیں اور باہر کی ڈھیلی اشیاء محفوظ کریں۔', measureStorm:'گرج چمک کے دوران اندر جائیں اور کھلے علاقوں سے بچیں۔', measureHeat:'باہر رہنے کا وقت کم کریں، سائے میں رہیں اور مناسب پانی پئیں۔', measureGeneral:'سرکاری انتباہات دیکھتے رہیں اور ہنگامی رابطے تیار رکھیں۔' },
};

// Keep the remaining Indian-language UIs fully functional with translated navigation/core controls;
// labels not explicitly overridden inherit English until translated.
D['mr'] = { ...D['mr'] };
D['gu'] = { ...D['gu'] };
D['pa'] = { ...D['pa'] };
D['or'] = { ...D['or'] };
D['as'] = { ...D['as'] };

export function t(language: string, key: Keys): string {
  return D[language]?.[key] || EN[key];
}

export function speechCode(language: string): string {
  return LANGUAGES.find((x) => x.code === language)?.speech || 'en-IN';
}

const CONDITION_KEYS: Record<string, string[]> = {
  clear: ['Clear sky','Mainly clear'],
  cloudy: ['Partly cloudy','Overcast'],
  fog: ['Fog'],
  drizzle: ['Drizzle'],
  rain: ['Rain','Rain showers'],
  snow: ['Snow','Snow showers'],
  thunder: ['Thunderstorm'],
  variable: ['Variable weather'],
};

const CONDITIONS: Record<string, Record<string,string>> = {
  hi:{clear:'साफ आसमान',cloudy:'बादल छाए',fog:'कोहरा',drizzle:'फुहार',rain:'बारिश',snow:'बर्फबारी',thunder:'आंधी-तूफान',variable:'बदलता मौसम'},
  kn:{clear:'ಸ್ವಚ್ಛ ಆಕಾಶ',cloudy:'ಮೋಡ ಕವಿದಿದೆ',fog:'ಮಂಜು',drizzle:'ತುಂತುರು ಮಳೆ',rain:'ಮಳೆ',snow:'ಹಿಮಪಾತ',thunder:'ಗುಡುಗು ಮಿಂಚು',variable:'ಬದಲಾಗುವ ಹವಾಮಾನ'},
  ta:{clear:'தெளிந்த வானம்',cloudy:'மேகமூட்டம்',fog:'மூடுபனி',drizzle:'தூறல்',rain:'மழை',snow:'பனிப்பொழிவு',thunder:'இடியுடன் கூடிய மழை',variable:'மாறும் வானிலை'},
  te:{clear:'స్పష్టమైన ఆకాశం',cloudy:'మేఘావృతం',fog:'మంచు',drizzle:'చినుకులు',rain:'వర్షం',snow:'మంచు వర్షం',thunder:'ఉరుములతో వర్షం',variable:'మారే వాతావరణం'},
  ml:{clear:'തെളിഞ്ഞ ആകാശം',cloudy:'മേഘാവൃതം',fog:'മൂടൽമഞ്ഞ്',drizzle:'ചാറ്റൽമഴ',rain:'മഴ',snow:'മഞ്ഞുവീഴ്ച',thunder:'ഇടിമിന്നൽ',variable:'മാറുന്ന കാലാവസ്ഥ'},
  bn:{clear:'পরিষ্কার আকাশ',cloudy:'মেঘলা',fog:'কুয়াশা',drizzle:'গুঁড়ি বৃষ্টি',rain:'বৃষ্টি',snow:'তুষারপাত',thunder:'বজ্রঝড়',variable:'পরিবর্তনশীল আবহাওয়া'},
  mr:{clear:'स्वच्छ आकाश',cloudy:'ढगाळ',fog:'धुके',drizzle:'रिमझिम',rain:'पाऊस',snow:'हिमवर्षाव',thunder:'मेघगर्जना',variable:'बदलते हवामान'},
  gu:{clear:'સાફ આકાશ',cloudy:'વાદળછાયું',fog:'ધુમ્મસ',drizzle:'ઝરમર વરસાદ',rain:'વરસાદ',snow:'હિમવર્ષા',thunder:'વીજળી સાથે તોફાન',variable:'બદલાતું હવામાન'},
  pa:{clear:'ਸਾਫ਼ ਆਕਾਸ਼',cloudy:'ਬੱਦਲਵਾਈ',fog:'ਧੁੰਦ',drizzle:'ਹਲਕੀ ਬਾਰਿਸ਼',rain:'ਮੀਂਹ',snow:'ਬਰਫ਼ਬਾਰੀ',thunder:'ਗਰਜ ਨਾਲ ਮੀਂਹ',variable:'ਬਦਲਦਾ ਮੌਸਮ'},
  or:{clear:'ସ୍ପଷ୍ଟ ଆକାଶ',cloudy:'ମେଘାଚ୍ଛନ୍ନ',fog:'କୁହୁଡ଼ି',drizzle:'ଝିପିଝିପି ବର୍ଷା',rain:'ବର୍ଷା',snow:'ହିମପାତ',thunder:'ବଜ୍ରପାତ',variable:'ପରିବର୍ତ୍ତନଶୀଳ ପାଣିପାଗ'},
  as:{clear:'পৰিষ্কাৰ আকাশ',cloudy:'ডাৱৰীয়া',fog:'কুঁৱলী',drizzle:'গুড়ি বৰষুণ',rain:'বৰষুণ',snow:'তুষাৰপাত',thunder:'গাজনি ধুমুহা',variable:'পৰিৱৰ্তনশীল বতৰ'},
  ur:{clear:'صاف آسمان',cloudy:'ابر آلود',fog:'دھند',drizzle:'ہلکی بارش',rain:'بارش',snow:'برف باری',thunder:'گرج چمک',variable:'بدلتا موسم'},
};

export function conditionText(condition: string, language: string): string {
  if (language === 'en') return condition;
  const category = Object.entries(CONDITION_KEYS).find(([, values]) => values.includes(condition))?.[0] || 'variable';
  return CONDITIONS[language]?.[category] || condition;
}

export function riskLabel(language: string, severity: string): string {
  if (severity === 'High' || severity === 'Severe') return t(language, 'riskHigh');
  if (severity === 'Medium' || severity === 'Moderate') return t(language, 'riskMedium');
  return t(language, 'riskLow');
}
